---
title: "Mutate Demo !"
output: html_notebook
---

# Load in Packages

```{r, echo = F, message = F, warning = F}
if(!require(pacman)) install.packages("pacman")
pacman::p_load(knitr, 
               here, 
               janitor,
               tidyverse)

```

# Load in Data

```{r}
diarrhea_mali <- read_csv(here("data/mutate_example_diarrhea_mali.csv"))

View(diarrhea_mali)

# clean names
diarrhea_mali_clean <- diarrhea_mali %>%
  janitor::clean_names()

#select just a few columns for the examples below
diarrhea_mali_clean <- diarrhea_mali_clean %>%
  select(code_patient, age_mois, sexe, nombre_selle)

diarrhea_mali_clean
```

# Mutate & Variable Types

We make sure categories are factors and numbers are numerical values.

Here we change variables in-place. (we do not create new variables)

```{r}
diarrhea_mali_clean <- diarrhea_mali_clean %>%
  mutate(sexe = as.factor(sexe),
         age_mois = as.numeric(age_mois),
         nombre_selle = as.numeric(nombre_selle))

diarrhea_mali_clean
```

# Mutate & Transforming Variables

From the age in months to the age in years.

Here we make a new variable: `age_years`

```{r}
diarrhea_mali_clean <- diarrhea_mali_clean %>%
  mutate(age_years = age_mois /12)

diarrhea_mali_clean
```
